### ISSUE TITLE
vendor/pixelfear/oauth2-dropbox/ folder empty

### ISSUE THREAD

**Issue by leblangi** [rabser/moodle-auth_googleoauth2#179]
This is a regression cause by this fix :
https://github.com/mouneyrac/moodle-auth_googleoauth2/commit/3ed0166a84a02d1aa280fcda6ba04e7c5a6c9bce

The folder vendor/pixelfear/oauth2-dropbox/ is now empty and there is an error because a class is this folder is missing.

To reproduce: 
Clear the vendor folder, reinstall the plugin and try to loggin
You will see an error or a blank page
Clearing the vendor folder and reinstall it with composer fix this.

**Comment by mouneyrac** [comment]
I removed the entire vendor folder (like recommended by composer), people will have to build it from now how explained in the readme.
cheers,
jerome
