### ISSUE TITLE
Error fetching OAuth2 access token, message: 'invalid_client'

### ISSUE THREAD

**Issue by tillmad** [rabser/moodle-auth_googleoauth2#182]
This is the sporadic issue that I described on the moodle plugin directory page.  It is sporadic - I have had it happen once on my iPad a month ago, but not since.  Other students tend to have it more often.  A student finally sent in a screenshot of the error.
![unnamed](https://cloud.githubusercontent.com/assets/15927035/11274575/1612e622-8e9f-11e5-9c2d-a64c98fc1a67.jpg)
##

**Comment by tillmad** [comment]
I posted this in another thread, but I also got this error this morning on my Mac using Chrome
<img width="789" alt="screen shot 2015-11-19 at 8 22 49 am" src="https://cloud.githubusercontent.com/assets/15927035/11274651/65952b2e-8e9f-11e5-9420-1c28cfa9fb65.png">

**Comment by mouneyrac** [comment]
Hi (tillmad?),
what is the url of your login page so we can look at it.
cheers,
Jerome

PS: on the first screenshot I see you are already login, how do you trigger the login process been still logged in?

**Comment by tillmad** [comment]
So I reset the Client Secret and put the new secret into Moodle and it started working consistently again.

Today at least, this issue was popping up using the Google Drive repository rather than the initial login.  Before today though all I saw was the Oauth2 error, which made me assume it was your plugin.  

Our server is configured to only allow access from within our email domain (@mcgill-toolen.org or @mctstudents.org).  The login page is http://www.mctmoodle.org/moodle/login/index.php

**Comment by tillmad** [comment]
So I reset the Client Secret and put the new secret into Moodle and it has
seemingly started working consistently again.

Today at least, this issue was popping up using the Google Drive repository
rather than the initial login. When students would go to submit an
assignment they could click on the Google Drive repository, and then they
have to log in to their account. They could get so far as to either logging
in to their school gmail account, or selecting the correct account, but
rather than redirecting properly (I think), this error would pop up.

Before today though all I saw was the Oauth2 error, which made me assume it
was your plugin.

Our server is configured to only allow access from within our email domain
(@mcgill-toolen.org or @mctstudents.org). The login page is
http://www.mctmoodle.org/moodle/login/index.php

Honestly - now that I think about it more, this could have been my fault
all along with a messed up client secret that I forgot to change a few
weeks back when I changed some things around.  I bet I changed it on the
authentication plugin page, but forgot to change it on the repository page
which is why I was able to log in but not use the google drive.  Of course
this means it wouldn't be your plugin at all, but rather user error by me.


Thanks for your hard work,

Daniel Tillman

Daniel Tillman
IT dept. McGill-Toolen Catholic HS
www.mcgill-toolen.org

**Comment by mouneyrac** [comment]
hum this is interesting I actually never tested google drive with oauth2 together... I wonder if google let you have multiple key/secret for the same domain - which maybe you would need as the redirect url is going to be different for both oauth2 plugin and google drive... now it makes sense that some provider allow multiple redirect urls for the same domain (can't remember if Google does it, if yes it would explain that both Google drive and Oauth2 plugin work). Let me know if something doesn't work in the future.

**Comment by tillmad** [comment]
It lets you set multiple redirects - but I wonder if something is getting
confused between the redirects.  I will set up a 2nd oauth2 client in
Google and set the second one for the Google Drive repository.

Daniel Tillman
IT dept. McGill-Toolen Catholic HS
www.mcgill-toolen.org



On Thu, Nov 19, 2015 at 10:31 PM, Jérôme Mouneyrac <notifications@github.com

**Comment by digitalarchitects** [comment]
I have a solid error in my new configuration that is the same. I get the login page. I chose login with google. It them prompts for which google account you want to use. You get the authorisation page that asks that you want to share your details. Here you click allow, and after that I get a moodle page that states Exception Invalid_client. 
I am looking for pointers as to where in my setup I missed something, thanks.

**Comment by rabser** [comment]
I'm closing this issue: too old. If you have not solved your errors, please re-open another issue specifying moodle and plugin version in use.
