### ISSUE TITLE
Same e-mail with different account error message needs to be modified

### ISSUE THREAD

**Issue by MelvRom** [rabser/moodle-auth_googleoauth2#191]
Currently, we are using the Facebook, Google + and Linkedin connection methods. When a user tries to login using one of the three, the plugin checks if the e-mail from that account doesn't already exist within the moodle database. If so, it displays a misleading error message that should be changed.

_Before testing this, you should make sure that the e-mail you're going to use is not already attached to a user._
To display the error message, you must:
1. Create a manual account with that has the same e-mail address as one of your social media accounts.
2. Try to connect with one of your social media account that has the same e-mail.
   **Result:** You receive an error message implying that it's an authentication method error when it's not (see attached pic).

![message_error_existantsameemail](https://cloud.githubusercontent.com/assets/8960380/12787151/23cf20c4-ca62-11e5-81d3-4a08554d9488.png)

The message that should appear could be something like (suggestion): **"An account with the same e-mail address already exist, please choose another authentication method or contact the site administrator"**.
##

**Comment by mouneyrac** [comment]
Thanks for the report, it is a good improvement to do.

**Comment by rabser** [comment]
Embedded in the next/new release, closing this issue, thanks.
