### ISSUE TITLE
Still not getting user portrait / profile picture from Facebook login (or Google+)

### ISSUE THREAD

**Issue by Coincoinlapin** [rabser/moodle-auth_googleoauth2#210]
Hi, I was under the impression that the latest plugin version was supposed to extract profile pictures upon first login but It doesn't work for me (Moodle 3). I've tested this with new users from Facebook & Google+
Am I doing anything wrong?

**Comment by mouneyrac** [comment]
from memory it works. Are you using the last version of the plugin? With Moodle 3.0? 3.1?

**Comment by rabser** [comment]
In the new release the profile picture will be correctly extracted from almost every provider. stay tuned with this project.
