### ISSUE TITLE
guzzle 3 is deprecated

### ISSUE THREAD

**Issue by mouneyrac** [rabser/moodle-auth_googleoauth2#221]
guzzle/guzzle suggests installing guzzlehttp/guzzle (Guzzle 5 has moved to a new package name. The package you have installed, Guzzle 3, is deprecated.)
depotwarehouse/oauth2-bnet suggests installing illuminate/support (Laravel integration)
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
Writing lock file

this should be fixed once we move to the last phpleague version

**Comment by rabser** [comment]
the new release installs only guzzlehttp/guzzle~.
