### ISSUE TITLE
Save Button not there

### ISSUE THREAD

**Issue by nelliemuller** [rabser/moodle-auth_googleoauth2#229]
The save button is not there anymore. I'm using Essential Theme.

**Comment by mouneyrac** [comment]
Hi Nellie, it is an known issue. If you refresh the login page they should reappear (somehow something with the cache or probably the way JS is loaded. A workaround solution is to hardcode the call to the buttons in the theme layout.)

**Comment by mouneyrac** [comment]
just noticed it is a duplicate of 225.

**Comment by rabser** [comment]
Did you solved ?

**Comment by nelliemuller** [comment]
Hi Sergio,

Yes, thank you. I increased the memory of the Moodle site and the save icon
appeared again.

Thank you.



Warm wishes,

Dr. Nellie Deutsch <http://goo.gl/7BgeKM>
Education Technology & Leadership Consultant
Organizes MOOCs & Free Online Events
Moodle for Teachers Free Training <https://moodle4teachers.org>
Moodle for Kids Projects <http://moodle4kids.org>
Ed Media Executive Committee Member
<https://www.aace.org/conf/edmedia/committeeEC.htm>
+1.6479640183
[image: Linkedin] <http://ca.linkedin.com/in/nelliemuller>[image: Facebook]
<http://www.facebook.com/drnelliedeutsch>[image: Twitter]
<http://twitter.com/nelliemuller>

**Comment by rabser** [comment]
thanks for the prompt reply.
