### ISSUE TITLE
Facebook_redirect.php

### ISSUE THREAD

**Issue by doarg** [rabser/moodle-auth_googleoauth2#35]
Hey mates, I got this error does anyone knows how to fix?

error/facebook_failure

Meer informatie over deze fout

Debug info: 
Error code: facebook_failure
$a contents: 

Stack trace: line 11 of /auth/googleoauth2/facebook_redirect.php: moodle_exception thrown

this is in the facebook_redirect.php

<?php

/*
- Get facebook code and call the normal login page
- Needed to add the parameter authprovider in order to identify the authentication provider
  */
  require('../../config.php');
  $code = optional_param('code', '', PARAM_TEXT); //Google can return an error

if (empty($code)) {
    throw new moodle_exception('facebook_failure');
}

$loginurl = '/login/index.php';
if (!empty($CFG->alternateloginurl)) {
    $loginurl = $CFG->alternateloginurl;
}
$url = new moodle_url($loginurl, array('code' => $code, 'authprovider' => 'facebook'));
redirect($url);
?>

**Comment by johnps** [comment]
Hi Doarg, I'm facing the same error as you did. How did you correct this in the FB app?
