### ISSUE TITLE
Error code: couldnotgetgoogleaccesstoken

### ISSUE THREAD

**Issue by jaimemontoya** [rabser/moodle-auth_googleoauth2#97]
I can log in successfully using Windows Live. When I try to log in using Google, this is what I see:

The authentication provider sent us a communication error. Please try to sign-in again.

Debug info:Error code: couldnotgetgoogleaccesstoken

Stack trace:

```
line 436 of /auth/googleoauth2/auth.php: moodle_exception thrown
line 92 of /login/index.php: call to auth_plugin_googleoauth2->loginpage_hook()
```

I went to examine this source code: https://github.com/mouneyrac/moodle-auth_googleoauth2/blob/master/auth.php#L160

I noticed that the problem happens on line 156: https://github.com/mouneyrac/moodle-auth_googleoauth2/blob/master/auth.php#L156

When I print out the value of the variable $postreturnvalues, this is what I get:

Failed to connect to 2001:4860:400b:c01::54: Network is unreachable

If I simply try to do this:

$postreturnvalues = $curl->get('https://accounts.google.com/o/oauth2/token');
print_r($postreturnvalues);

The result is:

Failed to connect to 2607:f8b0:400e:c02::54: Network is unreachable

Do you have any ideas that can help me to fix the issue? I suspect it has something to do with the configurations or restrictions from my web hosting provider, Bluehost. I am using Bluehost Plus with a dedicated IP address but Moodle is on a shared server. I think the problem has something to do with this: https://groups.google.com/forum/#!topic/adwords-api/6o6fKbvluNw

**Comment by guillefd** [comment]
I came up with this same error message yesterday (couldnotgetgoogleaccesstoken), after a few hours of debugging, recognized the error was in the extension setup: I left a blank space at the end when copy/pasted the "Client Secret".
Hope it helps someone else.
Great work!

**Comment by mouneyrac** [comment]
Hi Guillermo,
thank you for your donation! It is the first donation I ever received :) It makes me very happy :)
Cheers,
Jerome

**Comment by guillefd** [comment]
Hi Jerome, you´re welcome and thank you! for sharing the plugin with the community, great work!
